Models/Monitor/PlanListModel.cs
namespace NationalDisplay.Models;

public class PlanListModel{
    List<PlanInfo> planInfoList = new List<PlanInfo>();
    
    public PlanModel LoadPlanImage(string id)
    {
        Console.WriteLine("Load plan : " + id);

        PlanModel model = new PlanModel();

        PipeClient.command = 3;
        PipeClient.planId = id;
        PipeClient.Start();

        // 플랫폼에서 통신으로 도면 정보, 도면 ID와 일치하는 센서 가져오기
        // 센서에는 도면 ID가 포함되어 있다.

        return model;
    }

    public List<PlanInfo> LoadPlanListInfo()
    {
        planInfoList.Clear();

        PipeClient.command = 4;
        PipeClient.Start();
        // 도면 개수 확인하기
        // 도면 개수 만큼 planInfoList.Add(LoadPlanInfo)

        return planInfoList;
    }

    public PlanInfo LoadPlanInfo()
    {
        PlanInfo info = new PlanInfo();

        // 플랫폼에 요청 후 수신하기

        return info;
    }
}

public class PlanInfo{
    string id;
    string address;
    string buildingName;
    string dong;
    string floor;
    string ho;
}

Models/Monitor/PlanModel.cs
namespace NationalDisplay.Models;

public class PlanModel{
    public string id;
    public string address;
    public string[] sendsorId;
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NationalDisplay.Models;

namespace NationalDisplay.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;

namespace NationalDisplay.Controllers;

public class MainController: Controller
{
    public IActionResult ManageAccount()
    {
        
        return RedirectToAction("ManageAccountRedirect", "Main");
        // return View("/views/home/monitor/manageaccount.cshtml");
    }

    public IActionResult ManageAccountRedirect()
    {
        if(!AccountController.isLogin){
            return NoContent();
        }
        return View("/views/home/monitor/manageaccount.cshtml");
    }

    public IActionResult Display()
    {
            PlanListController p = new PlanListController();
            return p.Index();
    }
    public IActionResult Index()
    {
        if(!AccountController.isLogin){
            return NoContent();
        }
        return View("/views/home/monitor/main.cshtml");
    }

    public IActionResult Login()
    {
        AccountController.isLogin = false;
        Console.WriteLine("Login page");
        return View("/views/home/monitor/Login.cshtml");
    }
}

Controllers/Monitor/PlanController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NationalDisplay.Models;
using Microsoft.AspNetCore.SignalR;
using System.Web;

namespace NationalDisplay.Controllers;

public class PlanController : Controller
{
    static public List<SensorData> sensorList = new List<SensorData>();
    static public int indexTest = 0;
    // [Route("home/monitor")]
    public IActionResult MonitorPlan()
    {
        if(!AccountController.isLogin){
            return NoContent();
        }
        Console.WriteLine("Monitor plan");

        // SensorData s = new SensorData();
        // s.id = 1;
        // s.gas = 2;
        // s.smoke = 3;
        // s.temp = 4;
        // sensorList.sensorList.Add(s);

        return View("/views/home/monitor/plan.cshtml");
    }

    public void GetSensorPosition(string firstName, string lastName)
    {
        Console.WriteLine("Get Sensor : {0}, {1}", firstName, lastName);
    }
}

public class SensorHub: Hub
{
    public async Task SendSensorData(string u, string m)
    {
        // PlanController.sensorList = new List<SensorData>();
        // SensorData sensor = new SensorData();
        // sensor.id = 1;
        // sensor.smoke = 100 + PlanController.indexTest;
        // sensor.gas = 200 + PlanController.indexTest;
        // sensor.temp = 300 + PlanController.indexTest;
        // PlanController.sensorList.Add(sensor);

        // sensor = new SensorData();
        // sensor.id = 2;
        // sensor.smoke = 500 + PlanController.indexTest;;
        // sensor.gas = 600 + PlanController.indexTest;
        // sensor.temp = 700 + PlanController.indexTest;
        // PlanController.sensorList.Add(sensor);
        // PlanController.indexTest++;
 
        int index = 0;
        foreach(var s in PlanController.sensorList){
            List<string> list = new List<string>();

            list.Add(s.id.ToString());
            list.Add(s.smoke.ToString());
            list.Add(s.temp.ToString());
            list.Add(s.gas.ToString());

            int[] pos = LoadSensorPosition((int)s.id);
            list.Add(pos[0].ToString());
            list.Add(pos[1].ToString());

            await Clients.All.SendAsync("ReceiveSensorData", list, index);
            index++;
            
        }
    }

    public async Task SaveSensorPosition(int id, int x, int y)
    {
        byte[] buf = new byte[12];
        buf[0] = (byte)(id >> 24);
        buf[1] = (byte)(id >> 16);
        buf[2] = (byte)(id >> 8);
        buf[3] = (byte)(id >> 0);
        buf[4] = (byte)(x >> 24);
        buf[5] = (byte)(x >> 16);
        buf[6] = (byte)(x >> 8);
        buf[7] = (byte)(x >> 0);
        buf[8] = (byte)(y >> 24);
        buf[9] = (byte)(y >> 16);
        buf[10] = (byte)(y >> 8);
        buf[11] = (byte)(y >> 0);
        string folderPath = "wwwroot/sensor_pos/";
        DirectoryInfo di = new DirectoryInfo(folderPath);
        if(!di.Exists){
            di.Create();
        }
        FileStream fs = new FileStream(String.Format("wwwroot/sensor_pos/sensor{0}", id), FileMode.OpenOrCreate, FileAccess.Write);
        fs.Write(buf, 0, 12);
        fs.Close();
        Console.WriteLine("SaveSensorPosition:{0}, {1}, {2}", id, x, y);
    }

    public int[] LoadSensorPosition(int id)
    {
        int[] pos = new int[2];

        string folderPath = "wwwroot/sensor_pos/";
        string filePath = String.Format("wwwroot/sensor_pos/sensor{0}", id);
        DirectoryInfo di = new DirectoryInfo(folderPath);
        if(!di.Exists || !File.Exists(filePath)){
            pos[0] = 100;
            pos[1] = 100;
            return pos;
        }
        FileStream fs = new FileStream(filePath, FileMode.Open);
        BinaryReader br = new BinaryReader(fs);
        byte[] buf = br.ReadBytes(12);

        pos[0] = (buf[4] << 24) | (buf[5] << 16) | (buf[6] << 8) | (buf[7] << 0);
        pos[1] = (buf[8] << 24) | (buf[9] << 16) | (buf[10] << 8) | (buf[11] << 0);

        if(pos[0] > 1000){
            pos[0] = 100;
        }
        if(pos[1] > 500){
            pos[1] = 100;
        }

        // Console.WriteLine("LoadSensorPosition:{0} {1}", pos[0], pos[1]);
        fs.Close();
        return pos;
    }
}

public class ChatHub: Hub
{
    public async Task SendMessage(string user, string message)
    {
        List<string> list = new List<string>();
        Console.WriteLine("SignalR send");
        string temp = "test";
        // PlanController.indexTest++;
        list.Add("a");
        list.Add("b");
        foreach(var e in list){
            
            temp = PlanController.indexTest.ToString();
            await Clients.All.SendAsync("ReceiveMessage", e, temp);
            PlanController.indexTest++;
        }
        // await Clients.All.SendAsync("ReceiveMessage", list, temp);
    }
}

Controllers/Monitor/PlanListController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NationalDisplay.Models;

namespace NationalDisplay.Controllers;

public class PlanListController : Controller
{
    static public List<string[]> planListBuf = new List<string[]>();
 
    public Plan plan = new Plan();

    private PlanListModel planListModel = new PlanListModel();
    // [Route("home/planlist")]
    public IActionResult Index()
    {
        if(!AccountController.isLogin){
            return NoContent();
        }
        Console.WriteLine("Plan list");

        planListBuf.Clear();
        planListModel.LoadPlanListInfo();
        while(!PipeClient.sendComplete);
        plan.planList = planListBuf;

        return View("/views/home/monitor/planlist.cshtml", plan);
        // return NoContent();
    }

    public void GetSensorPosition(string firstName, string lastName)
    {
        Console.WriteLine("Get Sensor : {0}, {1}", firstName, lastName);
    }

    public IActionResult LoadPlan(string id)
    {
        if(!AccountController.isLogin){
            return NoContent();
        }
        Console.WriteLine("Plan id : " + id);

        SensorTask.planId = id;

        PlanListModel planList = new PlanListModel();
        PlanModel planModel = planList.LoadPlanImage(id);



        while(!PipeClient.sendComplete);

        return View("views/home/monitor/plan.cshtml", PlanController.sensorList);
    }

    public IActionResult LoadPlanList()
    {        
        if(!AccountController.isLogin){
            return NoContent();
        }
        plan.planList = planListBuf;
        foreach(var p in planListBuf){
            Console.WriteLine("aa:" + p[0]);
        }

        return View("/views/home/monitor/planlist.cshtml", plan);
    }
}

public class Plan{
    public List<string[]> planList = new List<string[]>(); 
}

Views/Home/Monitor/LogInfo.cshtml
@using Npgsql
@{

}
<head>
  @* <script type="text/javascript" src="http://code.jquery.com/jquery-3.6.0.js"></script> *@
    <script src="~/js/Monitor/planlist.js"></script>
    <link rel="stylesheet" href="~/css/monitor/loginfo.css?after">
</head>


<body>
    
    <div id="wrapper">
        <div class="region_title">
            로그 정보
        </div>
        <form asp-controller="Account" asp-action="DownloadDocument" method="post" enctype="multipart/form-data">
                <input id="button_log_info" class="button" type="submit" value="로그 정보 다운로드">
            </form>
        <table border=3 id="table_detail" align=center cellpadding=10>

            <tr>
                <th>ID</th>
                <th>접속 시간</th>
                <th>접속 여부</th>
                <th>IP</th>
            </tr>
            <tbody>
            @using (var conn = new NpgsqlConnection(
                    "host=localhost;username=postgres;password=1234;database=displaydb"))
            {
            try
                {
                    conn.Open();
                    using (var cmd = new NpgsqlCommand())
                    {
                        Console.WriteLine("Start read log_info");
                        cmd.Connection = conn;
                        cmd.CommandText = String.Format("SELECT id, time, pass, ip FROM log_info ORDER BY time DESC");

                        string folder = "c:/safe";
                        DirectoryInfo di = new DirectoryInfo(folder);
                        if(di.Exists == false) di.Create();

                        using (StreamWriter csv = new StreamWriter(@"C:\safe\log_info_d.csv"))
                        {
                            using (var reader = cmd.ExecuteReader())
                            {
                                Console.WriteLine(cmd.CommandText);
                                while (reader.Read())
                                {

                                    string content = "";
                                    content = reader.GetString(0) + "," + reader.GetString(1) + "," + reader.GetString(2) + "," + reader.GetString(3);
                                    csv.WriteLine(content);


                                    string pName = reader.GetString(0);
                                    Console.WriteLine("reader test : " + pName);

                                    Console.Write(reader.GetString(0) + " ");
                                    @* Console.Write(reader.GetString(1) + " ");
                                        Console.Write(reader.GetString(2) + " ");
                                        Console.Write(reader.GetString(3) + " ");
                                        Console.Write(reader.GetString(4) + " "); *@
                                    @* Console.Write(reader.GetString(5) + " "); *@
                                    @* Console.Write(reader.GetString(6) + " "); *@
                                    Console.Write("\n");

                                    @* int length = 0;
                                        while(reader.Read()){
                                        length++;
                                        } *@

                                    <tr>
                                        @for (int i = 0; i < 4; i++)
                                        {
                                            if (reader.IsDBNull(i))
                                            {
                                                Console.WriteLine("String is null");
                                                <td></td>
                                            }
                                            else
                                            {
                                                <td>@reader.GetString(i)</td>
                                            }
                                        }
                                    </tr>
                                }
                            }
                        }
                    }
                }
            catch (Exception ex)
            {

            }
        }
        </tbody>
        </table>
    </div>
</body>

Views/Home/Monitor/Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <div class="title">
        재난 관리 관제 소프트웨어 v1.0
    </div>    
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        .login {
            width: 500px;
            margin: 200px auto auto auto;
        }
        .title{
            margin: 0px 0px 0px 150px;
        }
        .id{
            margin: 20px 0px 0px 160px;
        }
        .pw{
            margin: 20px 0px 0px 160px;
        }
        .button{
            margin: 20px 0px 0px 160px;
        }
    </style>
    <link rel="stylesheet" href="~/css/monitor/login.css?after">
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/monitor/login.js?after"></script>  
</head>
<body>
    <div class = "login">
        <h1 class = "title_sub">로그인</h1>
        <hr>
            <form asp-controller="Account" asp-action="CheckLogin" method="post" enctype="multipart/form-data">
                <p class = "id">ID: <input id="id" type="text" name="id" maxlength='50'/></p>
                <p class = "pw">PW: <input id="pw" type="password" name="password" maxlength='50'/></p>
                <input class="button" type="submit" value="로그인" onclick="login()">
            </form>
            @* <form method="post">
                <button class="button" id="btn-2" asp-controller="Account" asp-action="ChangePasswordPage">비밀번호 변경</button>
            </form>
            <form method="post">
                <button class="button" id="btn-2" asp-controller="Account" asp-action="LogInfo">로그 정보</button>
            </form> *@
        <hr>
    </div>
</body>
</html>

<style>

.title{
    text-align: center;
    font-size: 80px;
    color:beige
}

body {
    background: rgb(34,57,73);
    font-size: 150.5%;
  }
</style>

Views/Home/Monitor/Main.cshtml
@{
    ViewData["Title"] = "Main Page";
}

<link rel="stylesheet" href="~/css/main/main.css?after">
<script src="~/js/main/main.js?after"></script>  

<!DOCTYPE html>

<header>

</header>
<body>
    <div class="title">
        재난 관리 관제 소프트웨어 v1.0
    </div>
    <form method="post">
        <button class="button_logout" id="logout" asp-controller="Account" asp-action="Logout">로그아웃</button>
    </form>
    <div class="container">
        <form method="get">
            @* @if(NationalDisplay.Controllers.AccountController.account_id == "master"){
          <button class="btn_add_sensor">계정 추가</button>
      } *@
      @if(NationalDisplay.Controllers.AccountController.account_id == "master"){
        <button class="button" id="btn-1" asp-controller="Main" asp-action="ManageAccount">계정 관리</button>
      }else{
          @* <button disabled class="button" id="btn-1" asp-controller="Main" asp-action="ManageAccount">계정 관리</button> *@
      }

            @* <button class="button" id="btn-1" asp-controller="Main" asp-action="ManageAccount">계정 관리</button> *@
        </form>
                    <form method="post">
                        <button class="button" id="btn-2" asp-controller="Account" asp-action="ChangePasswordPage">비밀번호 변경</button>
                    </form>
                    <form method="post">
                         @if(NationalDisplay.Controllers.AccountController.account_id == "master"){
                            <button class="button" id="btn-2" asp-controller="Account" asp-action="LogInfo">로그 정보</button>
                         }
                    </form>
        <form method="get">
            <button class="button" id="btn-2" asp-controller="Main" asp-action="Display">관제</button>
        </form>
    </div>
</body>

Views/Home/Monitor/ManageAccount.cshtml
@model NationalDisplay.Models.AccountModel
@using Npgsql
@{
  var currentCount = 0;

  void IncrementCount()
  {
    currentCount++;
  }
}
<head>
  <script type="text/javascript" src="http://code.jquery.com/jquery-3.6.0.js"></script>
  <link rel="stylesheet" href="~/css/monitor/manageaccount.css?after">
  <script src="~/js/signalr/dist/browser/signalr.js"></script>
  <script src="~/js/monitor/manageaccount.js?after"></script>  
  
</head>

<header>
</header>
<body>
  <div class="title">
        계정 등록
    </div>
    @* @if(NationalDisplay.Controllers.AccountController.account_id == "master"){
          <button class="btn_add_sensor">계정 추가</button>
      } *@
    <button class="btn_add_sensor">계정 추가</button>
  
  @* <button class="openBtn">Modal2</button> *@
  <table>
    <thread>
      <tr>
        <th>ID</th>
        <th>삭제</th>
      </tr>
    </thread>
    <tbody>
      @using (var conn = new NpgsqlConnection(
                    "host=localhost;username=postgres;password=1234;database=displaydb"))
        {
            try
            {
                conn.Open();
                using (var cmd = new NpgsqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandText = String.Format("SELECT * FROM sub_account ORDER BY id DESC");
                    using (var reader = cmd.ExecuteReader())
                    {
                        Console.WriteLine(cmd.CommandText);
                        while (reader.Read())
                        {
                            @* Console.Write(reader.GetString(0) + " ");
                            Console.Write(reader.GetString(1) + " ");
                            Console.Write(reader.GetString(2) + " ");
                            Console.Write(reader.GetString(3) + " ");
                            Console.Write(reader.GetString(4) + " ");
                            Console.Write(reader.GetString(5) + " ");
                            Console.Write(reader.GetString(6) + " ");
                            Console.Write("\n"); *@
                            
                            @* int length = 0;
                            while(reader.Read()){
                              length++;
                            } *@

                            <tr>
                              @for(int i = 0; i < 1; i++){
                                if(reader.IsDBNull(i)){
                                  Console.WriteLine("String is null");
                                  <td></td>
                                }
                                else{
                                  <th>@reader.GetString(i)</th>
                                }
                              }
                              @* <td>@reader.GetString(0)</td>
                              <td>@reader.GetString(1)</td>
                              <td>@reader.GetString(2)</td>
                              <td>@reader.GetString(3)</td>
                              <td>@reader.GetString(4)</td>
                              <td>@reader.GetString(5)</td>
                              <td>@reader.GetString(6)</td>
                              <td>@reader.GetString(7)</td> *@
                              <th>
                                <form asp-controller="Account" asp-action="RemoveSubAccount" method="post">
                                  <input type="hidden" value=@reader.GetString(0) name="id" />
                                  <input id="load_plan" type='submit' value="삭제" />
                                </form>
                              </th>
                            </tr>
                        }
                    }
                }
            }
            catch (Exception ex)
            {

            }
        }
    </tbody>
  </table>
  <div id="table_title_region">
    
  </div>
  <div id="table_item_region">
  </div>



  @* Chart *@
  @* <div class="chart">
    @using (var conn = new NpgsqlConnection(
                    "host=localhost;username=postgres;password=1234;database=nationaldb"))
        {
            try
            {
                conn.Open();
                using (var cmd = new NpgsqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandText = String.Format("SELECT * FROM sensor_info ORDER BY id DESC");
                    using (var reader = cmd.ExecuteReader())
                    {
                        Console.WriteLine(cmd.CommandText);
                        while (reader.Read())
                        {
                            Console.Write(reader.GetString(0) + " ");
                            Console.Write(reader.GetString(1) + " ");
                            Console.Write(reader.GetString(2) + " ");
                            Console.Write(reader.GetString(3) + " ");
                            Console.Write(reader.GetString(4) + " ");
                            Console.Write(reader.GetString(5) + " ");
                            Console.Write(reader.GetString(6) + " ");
                            Console.Write("\n");
                            <div class="sensor_info">

                              <p2>@reader.GetString(0)</p2>
                              <p2>@reader.GetString(1)</p2>
                              <p2>@reader.GetString(2)</p2>
                              <p2>@reader.GetString(3)</p2>
                              <p2>@reader.GetString(4)</p2>
                              <p2>@reader.GetString(5)</p2>
                              <p2>@reader.GetString(6)</p2>

                            </div>
                        }
                    }
                }
            }
            catch (Exception ex)
            {

            }
        }
  </div> *@
    @* Modal Popup 1 *@
  @* <button class="btn_add_sensor">센서 추가</button> *@
  <div class="background">
    <div class="window">
      <div class="popup">
        <form asp-controller="Account" asp-action="RegistSubAccount" method="post" id="regist_sub_account_form">
          <p id="sensor_info_br"></p><br>
          <p style="display:inline" class="sensor_info">ID</p>  <input type="text" class="sensor_info_input" id="sub_account_id" name="id" maxlength='50'><br>
          <p style="display:inline" class="sensor_info">Password</p>  <input type="text" class="sensor_info_input" id="sub_account_password" name="password" maxlength='50'><br>

          @* <p style="display:inline" class="sensor_info">좌표 X</p>  <input type="text" class="sensor_info_input" name="x"><br>
          <p style="display:inline" class="sensor_info">좌표 Y</p>  <input type="text" class="sensor_info_input" name="y"><br> *@
        </form>
        <button type="submit" form="regist_sub_account_form" class="close" onclick="createSubAccount()">추가</button>
        <button class="cancel">취소</button>
      </div>
    </div>
  </div>

  @* Modal Popup 2 *@
  @* <button class="openBtn">Modal2</button> *@
  <div class="modal hidden">
    <div class="bg"></div>
    <div class="modalBox">
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consectetur quam nobis quis corrupti amet maxime
        neque, optio, in illo, voluptatibus consequuntur! Rerum quo ea nulla qui, maxime consectetur magni soluta!</p>
      <button class="closeBtn">✖</button>
    </div>
  </div>
</body>

<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>

<style>
  #table_title_region {
    background: yellow;
    overflow: hidden;
  }

  p1 {
    float: left;
    padding: 30px;
  }
  p2{
    width: 6%;
    padding: 50px;
  }
</style>

Views/Home/Monitor/Password.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        .login {
            width: 500px;
            margin: 200px auto auto auto;
        }
        .title{
            margin: 0px 0px 0px 150px;
        }
        .pw1{
            margin: 0px 0px 0px 60px;
        }
        .pw2{
            margin: 0px 0px 0px 60px;
        }
        .button{
            margin: 20px 0px 0px 60px;
        }
    </style>

  <link rel="stylesheet" href="~/css/monitor/password.css?after">
  <script src="~/js/signalr/dist/browser/signalr.js"></script>
  <script src="~/js/monitor/password.js?after"></script>  
  

</head>
<body>
    <div class = "login">
        <h1 class = "title">비밀번호 재설정</h1>
        <hr>
            <form asp-controller="Account" asp-action="ChangePassword" method="post" enctype="multipart/form-data">
                <p class = "pw1">비밀번호 입력: <input id="pw" type="password" name="password0" maxlength='50'/></p>
                <p class = "pw1">새 비밀번호 입력: <input id="pw1" type="password" name="password1" maxlength='50'/></p>
                <p class = "pw2">새 비밀번호 재입력: <input id="pw2" type="password" name="password2" maxlength='50'/></p>
                <input class="button" type="submit" value="비밀번호 재설정" onclick="checkPassword()">
            </form>
        <hr>
    </div>
</body>
</html>

Views/Home/Monitor/PlanList.cshtml
@model NationalDisplay.Controllers.Plan


@{

}

<head>
    <script src="~/js/Monitor/planlist.js"></script>
    <link rel="stylesheet" href="~/css/monitor/planlist.css?after">
</head>

<body>
    <div id="wrapper">
        <div class="region_title">
            재난 관리 관제 소프트웨어 v1.0
        </div>
        <table border=3 id="table_detail" align=center cellpadding=10>

            <tr>
                <th>도면ID</th>
                <th>주소</th>
                <th>건물 이름</th>
                <th>동</th>
                <th>층</th>
                <th>호</th>
                <th>불러오기</th>
            </tr>
            @foreach(var info in Model.planList)
            {
                <tr onclick="showHideRow('hidden_row2');">
                    <td>@info[0]</td>
                    <td>@info[1]</td>
                    <td>@info[2]</td>
                    <td>@info[3]</td>
                    <td>@info[4]</td>
                    <td>@info[5]</td>
                    <td>
                        <form asp-controller="PlanList" asp-action="LoadPlan" method="get">
                            <input type="hidden" value="@info[0]" name="id" />
                            <input id="load_plan" type='submit' value="불러오기" />
                        </form>
                    </td>
                </tr>
            }


            @* <tr onclick="showHideRow('hidden_row2');">
                <td>Person-2</td>
                <td>25</td>
                <td>100000</td>
                <td>Web Designer</td>
                </tr>
                <tr id="hidden_row2" class="hidden_row">
                <td colspan=4>
                Person-2 is 25 years old and
                she is a web designer she earns
                100000 per month
                </td>
                </tr>

                <tr onclick="showHideRow('hidden_row3');">
                <td>Person-3</td>
                <td>35</td>
                <td>90000</td>
                <td>Cyber Security Expert</td>
                </tr>
                <tr id="hidden_row3" class="hidden_row">
                <td colspan=4>
                Person is 35 years old and he
                is a cyber security expert he
                earns 90000 per month
                </td>
                </tr>

                <tr onclick="showHideRow('hidden_row4');">
                <td>Person-4</td>
                <td>52</td>
                <td>200000</td>
                <td>Content Writer</td>
                </tr>
                <tr id="hidden_row4" class="hidden_row">
                <td colspan=4>
                Person-4 is 52 years old and he
                is a content writer he earns
                200000 per month
                </td>
                </tr>

                <tr onclick="showHideRow('hidden_row5');">
                <td>Person-5</td>
                <td>38</td>
                <td>400000</td>
                <td>Chief Executive</td>
                </tr>
                <tr id="hidden_row5" class="hidden_row">
                <td colspan=4>
                Person-5 is 38 years old and he
                is chief executive he earns
                400000 per month
                </td>
                </tr> *@
        </table>
    </div>
</body>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js">
</script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

<script type="text/javascript">
    function showHideRow(row) {
        $("#" + row).toggle();
    }
</script>

<style>

</style>